### ISSUE TITLE
folder of videos

### ISSUE THREAD

**Issue by ghost** [adafruit/pi_hello_video#1]
I cant, or dont know how, to play a folder of videos (loop alphabetical order).
Is this possible?

**Comment by tdicola** [comment]
Oh no problem pull the videos out so they are in the root of the USB stick/directory instead of inside a subfolder, then it should play them all in alphabetical order.

**Comment by ghost** [comment]
?  I dont get it...

I can:  $ hello_video.bin  --loop myvideo.h264 
And this is working fine.
But: hello_video.bin --loop *
or
 hello_video.bin --loop /folder/*

dont work.

I dont have any idea.

And btw, I am trying this, because the: pi_video_looper apliccation from adafruit website wont work with hello_video option  (works with omxplayer),  Calling hello_video.bin myvideo.h264 form cmd works

**Comment by tdicola** [comment]
Oh sorry I didn't realize you opened this on the hello video repo and not the video looper repo.  Actually it looks like hello video doesn't support passing in multiple files (like using the '*' syntax).  You'll want to use the video looper or even a shell script to iterate through running movies individually.  Lets followup on video looper issues in the other bug here: https://github.com/adafruit/pi_video_looper/issues/6
