### ISSUE TITLE
Videos stop before ending

### ISSUE THREAD

**Issue by ralcantaraperez** [adafruit/pi_hello_video#4]
As of commit https://github.com/raspberrypi/userland/commit/e0fc99d48fc7a1019e2c5f80f994108b3fe94ba5 there was a bug with some files. I've patched video.c with the same code and it runs fine.

> diff --git a/hello_video/video.c b/hello_video/video.c
> index ae87319..436f019 100644
> --- a/hello_video/video.c
> +++ b/hello_video/video.c
> @@ -190,7 +190,7 @@ static int video_decode_test(char *filename, int loop)
> 
> ```
>   // wait for EOS from render
>    ilclient_wait_for_event(video_render, OMX_EventBufferFlag, 90, 0, OMX_BUFFERFLAG_EOS, 0,
> ```
> -                              ILCLIENT_BUFFER_FLAG_EOS, 10000);
> -                              ILCLIENT_BUFFER_FLAG_EOS, -1);

```
   // need to flush the renderer to allow video_decode to disable its input port
   ilclient_flush_tunnels(tunnel, 0);
```

**Comment by tofuSCHNITZEL** [comment]
thanks a lot for this! I added the upstream fix here too.
