### ISSUE TITLE
Playing files bigger than 1920x1080

### ISSUE THREAD

**Issue by baronlanteigne** [adafruit/pi_hello_video#5]
I'm wondering if there's a quick fix for this because the files play smooth, very high bitrate and all... but any pixel above 2073600 (1920 \* 1080) will be glitched and green. I tried playing a 1728 x 1200 (same number of pixels) file and it's fine but a 1800 x 1200 will have the glitch.

It doesn't seem to be hardware limit but a limit in the software but I don't know it well enough to find and edit this.

**Comment by tdicola** [comment]
Unfortunately this is out of scope of this repository--the purpose of this repo is to slightly modify the Raspberry Pi foundation's GPU accelerated video playback example (hello_video) to do seamless looping.  Your best bet is to open this against the upstream code: https://github.com/raspberrypi/firmware/tree/master/opt/vc/src/hello_pi/hello_video  That said I have a feeling there's a hard limit to how big videos can be before the GPU can't do accelerated playback--1080p might be it.
