### ISSUE TITLE
how to change the path of the playlist folder?

### ISSUE THREAD

**Issue by matteoraggi** [adafruit/pi_hello_video#6]
pi_hello_video is automatucally playing videos that are into the usb pen.
How to configure pi_hello_video to automatically play videos stored for example into /home/pi/videos/ ?

**Comment by tdicola** [comment]
Check the usage from the guide for the video looper (note this repository is for the hello_video code that's modified for seamless looping): https://learn.adafruit.com/raspberry-pi-video-looper/usage  You want to use the file_reader configuration, scroll down the page to the file_reader section:

"file_reader controls where videos are found, either on USB drives or from a directory on the Raspberry Pi.  Again you can pick one of two options:
- usb_drive is the default and will search all attached USB drives for movies.  You can plug in a USB drive and it will automatically be searched for movies to play.
- directory will search a single directory on the Raspberry Pi for movies.  This is useful if you can't have a USB drive attached to the Raspberry Pi."
