### ISSUE TITLE
im having this issue

### ISSUE THREAD

**Issue by rikrikrik** [adafruit/pi_hello_video#7]
`Cloning into 'pi_hello_video'...
remote: Counting objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (23/23), done.
Checking connectivity... done.
make: Entering directory '/home/pi/pi_video_looper/pi_hello_video/libs/ilclient'
for i in ilclient.o ilcore.o; do (if test -e "$i"; then ( rm $i ); fi ); done
make: Leaving directory '/home/pi/pi_video_looper/pi_hello_video/libs/ilclient'
make: Entering directory '/home/pi/pi_video_looper/pi_hello_video/hello_video'
for i in video.o; do (if test -e "$i"; then ( rm $i ); fi ); done
make: Leaving directory '/home/pi/pi_video_looper/pi_hello_video/hello_video'
make: Entering directory '/home/pi/pi_video_looper/pi_hello_video/libs/ilclient'
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I../libs/ilclient -I../libs/vgfont -g -c ilclient.c -o ilclient.o -Wno-deprecated-declarations
ilclient.c:50:33: fatal error: interface/vcos/vcos.h: No such file or directory
compilation terminated.
../../Makefile.include:11: recipe for target 'ilclient.o' failed
make: *** [ilclient.o] Error 1
make: Leaving directory '/home/pi/pi_video_looper/pi_hello_video/libs/ilclient'
make: Entering directory '/home/pi/pi_video_looper/pi_hello_video/hello_video'
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I../libs/ilclient -I../libs/vgfont -g -c video.c -o video.o -Wno-deprecated-declarations
video.c:34:22: fatal error: bcm_host.h: No such file or directory
compilation terminated.
../Makefile.include:11: recipe for target 'video.o' failed
make: *** [video.o] Error 1
make: Leaving directory '/home/pi/pi_video_looper/pi_hello_video/hello_video'
root@orangepipc:/home/pi/pi_video_looper#
`

**Comment by tdicola** [comment]
Make sure you're using an official Raspbian Jessie or Stretch image.  The error is a failure to find the necessary Raspberry Pi video driver headers which are included with those images.  Notice this line:
```
fatal error: bcm_host.h: No such file or directory compilation terminated.
```
