### ISSUE TITLE
fatal error: bcm_host.h: No such file or directory

### ISSUE THREAD

**Issue by adhirmndl** [adafruit/pi_hello_video#8]
video.c:34:10: fatal error: bcm_host.h: No such file or directory
 #include "bcm_host.h"
          ^~~~~~~~~~~~
compilation terminated.
../Makefile.include:12: recipe for target 'video.o' failed

**Comment by tofuSCHNITZEL** [comment]
maybe you tried to compile it on something different than a raspberry pi?
see also:
https://raspberrypi.stackexchange.com/a/60459
